forecast_size: 16
backcast_size: 48  # 16 * 3

factor: 1
token_len: 4
nhid: 128
nhead: 8
dim_feedfwd: 512
nlayers: 24
dropout: 0.1
batch_size: 1024
test_col: "close"

lr: 1e-3
epochs: 100
init_weight_magnitude: 1e-1
